services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: document-intelligence-rag

    ports:
      - "8000:8000"

    environment:
      OLLAMA_HOST: http://host.docker.internal:11434
      OLLAMA_MODEL: llama3.2:3b
      EMBEDDING_MODEL: nomic-embed-text

    volumes:
      - ./data:/app/data

    extra_hosts:
      - "host.docker.internal:host-gateway"

    restart: unless-stopped